apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-registry
  labels:
    type: registry
    name: eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: service-image
        image: ghcr.io/pranjal-mukherjee/bootcamp117-backend-transaction-service:7
        ports:
        - containerPort: 8761
      imagePullSecrets: 
      - name: ghcr-secret
  selector:
    matchLabels:
      app: eureka-service
